linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gosec
    - prealloc
    - copyloopvar

issues:
  exclude-dirs:
    - vendor
    - test
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gosec

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
  goimports:
    local-prefixes: github.com/jongyunha/shrinkmap
  gosec:
    excludes:
      - G115

run:
  timeout: 5m
  go: '1.21'
  modules-download-mode: readonly
