version: "2"
run:
  go: "1.21"
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
        - name: package-comments
        - name: function-result-limit
          arguments: [4]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - mnd
        path: _test\.go
      - path: (.+)\.go$
        text: vendor
      - path: (.+)\.go$
        text: test
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
