linters:
  enable:
    - gofmt
    - golint
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gocritic
    - prealloc

run:
  deadline: 5m
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style