project_name: shrinkmap

before:
  hooks:
    - go mod tidy

release:
  github:
    owner: jongyunha
    name: shrinkmap
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{.Version}}"
  header: |
    ## ShrinkableMap v{{.Version}}

    For more information, please refer to the [documentation](https://pkg.go.dev/github.com/jongyunha/shrinkmap).

    ### Installation
    ```bash
    go get github.com/jongyunha/shrinkmap@v{{.Version}}
    ```
  footer: |
    **Full Changelog**: https://github.com/jongyunha/shrinkmap/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
      - go mod tidy

archives:
  - id: source
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_source
    format: tar.gz
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - '*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

signs:
  - cmd: gpg
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    signature: "${artifact}.sig"
    artifacts: checksum

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
