before:
  hooks:
    - go mod tidy

archives:
  - format: tar.gz
    files:
      - src/**/*
      - LICENSE*
      - README*
      - docs/**/*
      - '*.go'
      - go.mod
      - go.sum
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: jongyunha
    name: shrinkmap

  draft: false
  prerelease: auto

  name_template: "Release {{.Version}}"

  header: |
    ## ShrinkableMap {{.Version}} ({{ .Date }})

    See [CHANGELOG.md](CHANGELOG.md) for all changes.

    ### Installation
    ```bash
    go get github.com/jongyunha/shrinkmap@{{.Version}}
    ```

  footer: |
    ### Thanks!

    * Thanks to all contributors
    * Built with Go {{.Env.GO_VERSION}}
    * Full changelog: https://github.com/jongyunha/shrinkmap/blob/main/CHANGELOG.md

env:
  - GO_VERSION={{ .Env.GOVERSION }}
